#pragma once

#include <map>

class SignTables {
public:
	~SignTables() = default;

	SignTables(const SignTables&) = delete;

	SignTables(SignTables&&) noexcept = default;

	SignTables& operator=(const SignTables&) = default;

	SignTables& operator=(SignTables&&) noexcept = default;

	static SignTables& GetInstance() {
		static SignTables instance;
		return instance;
	}

	[[nodiscard]] std::pair<int, int> GetBounds(int n1, int n2) {
		return this->boundsTable_.at({ n1, n2 });
	}

private:
	SignTables() = default;

	std::map<std::pair<int, int>, std::pair<int, int>> boundsTable_ = {
		std::make_pair(std::make_pair(2, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(4, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(5, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(6, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(7, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(8, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(9, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(10, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(11, 2), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(12, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(13, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(14, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(15, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(16, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(17, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(18, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(19, 2), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(20, 2), std::make_pair(2, 0)),

		std::make_pair(std::make_pair(2, 3), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 3), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(4, 3), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(5, 3), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(6, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(7, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(8, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(9, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(10, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(11, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(12, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(13, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(14, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(15, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(16, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(17, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(18, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(19, 3), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(20, 3), std::make_pair(2, 0)),

		std::make_pair(std::make_pair(2, 4), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 4), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(4, 4), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(5, 4), std::make_pair(2, 9)),
		std::make_pair(std::make_pair(6, 4), std::make_pair(2, 9)),
		std::make_pair(std::make_pair(7, 4), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(8, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(9, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(10, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(11, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(12, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(13, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(14, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(15, 4), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(16, 4), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(17, 4), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(18, 4), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(19, 4), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(20, 4), std::make_pair(4, 0)),

		std::make_pair(std::make_pair(2, 5), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 5), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(4, 5), std::make_pair(2, 9)),
		std::make_pair(std::make_pair(5, 5), std::make_pair(2, 10)),
		std::make_pair(std::make_pair(6, 5), std::make_pair(3, 10)),
		std::make_pair(std::make_pair(7, 5), std::make_pair(3, 11)),
		std::make_pair(std::make_pair(8, 5), std::make_pair(3, 11)),
		std::make_pair(std::make_pair(9, 5), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(10, 5), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(11, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(12, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(13, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(14, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(15, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(16, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(17, 5), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(18, 5), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(19, 5), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(20, 5), std::make_pair(5, 0)),

		std::make_pair(std::make_pair(2, 6), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 6), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 6), std::make_pair(2, 9)),
		std::make_pair(std::make_pair(5, 6), std::make_pair(3, 10)),
		std::make_pair(std::make_pair(6, 6), std::make_pair(3, 11)),
		std::make_pair(std::make_pair(7, 6), std::make_pair(3, 12)),
		std::make_pair(std::make_pair(8, 6), std::make_pair(3, 12)),
		std::make_pair(std::make_pair(9, 6), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(10, 6), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(11, 6), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(12, 6), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(13, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(14, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(15, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(16, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(17, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(18, 6), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(19, 6), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(20, 6), std::make_pair(6, 0)),

		std::make_pair(std::make_pair(2, 7), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 7), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 7), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(5, 7), std::make_pair(3, 11)),
		std::make_pair(std::make_pair(6, 7), std::make_pair(3, 12)),
		std::make_pair(std::make_pair(7, 7), std::make_pair(3, 13)),
		std::make_pair(std::make_pair(8, 7), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(9, 7), std::make_pair(4, 14)),
		std::make_pair(std::make_pair(10, 7), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(11, 7), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(12, 7), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(13, 7), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(14, 7), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(15, 7), std::make_pair(6, 15)),
		std::make_pair(std::make_pair(16, 7), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(17, 7), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(18, 7), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(19, 7), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(20, 7), std::make_pair(6, 0)),

		std::make_pair(std::make_pair(2, 8), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 8), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 8), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 8), std::make_pair(3, 11)),
		std::make_pair(std::make_pair(6, 8), std::make_pair(3, 12)),
		std::make_pair(std::make_pair(7, 8), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(8, 8), std::make_pair(4, 14)),
		std::make_pair(std::make_pair(9, 8), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(10, 8), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(11, 8), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(12, 8), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(13, 8), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(14, 8), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(15, 8), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(16, 8), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(17, 8), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(18, 8), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(19, 8), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(20, 8), std::make_pair(7, 17)),

		std::make_pair(std::make_pair(2, 9), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 9), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 9), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 9), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(6, 9), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(7, 9), std::make_pair(4, 14)),
		std::make_pair(std::make_pair(8, 9), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(9, 9), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(10, 9), std::make_pair(5, 16)),
		std::make_pair(std::make_pair(11, 9), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(12, 9), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(13, 9), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(14, 9), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(15, 9), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(16, 9), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(17, 9), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(18, 9), std::make_pair(8, 18)),
		std::make_pair(std::make_pair(19, 9), std::make_pair(8, 18)),
		std::make_pair(std::make_pair(20, 9), std::make_pair(8, 18)),

		std::make_pair(std::make_pair(2, 10), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 10), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 10), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 10), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(6, 10), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(7, 10), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(8, 10), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(9, 10), std::make_pair(5, 16)),
		std::make_pair(std::make_pair(10, 10), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(11, 10), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(12, 10), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(13, 10), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(14, 10), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(15, 10), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(16, 10), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(17, 10), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(18, 10), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(19, 10), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(20, 10), std::make_pair(9, 20)),

		std::make_pair(std::make_pair(2, 11), std::make_pair(0, 0)),
		std::make_pair(std::make_pair(3, 11), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 11), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 11), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 11), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(7, 11), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(8, 11), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(9, 11), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(10, 11), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(11, 11), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(12, 11), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(13, 11), std::make_pair(7, 19)),
		std::make_pair(std::make_pair(14, 11), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(15, 11), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(16, 11), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(17, 11), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(18, 11), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(19, 11), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(20, 11), std::make_pair(9, 21)),

		std::make_pair(std::make_pair(2, 12), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 12), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 12), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 12), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 12), std::make_pair(4, 13)),
		std::make_pair(std::make_pair(7, 12), std::make_pair(5, 14)),
		std::make_pair(std::make_pair(8, 12), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(9, 12), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(10, 12), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(11, 12), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(12, 12), std::make_pair(7, 19)),
		std::make_pair(std::make_pair(13, 12), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(14, 12), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(15, 12), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(16, 12), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(17, 12), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(18, 12), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(19, 12), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(20, 12), std::make_pair(10, 22)),

		std::make_pair(std::make_pair(2, 13), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 13), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 13), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 13), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 13), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 13), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(8, 13), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(9, 13), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(10, 13), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(11, 13), std::make_pair(7, 19)),
		std::make_pair(std::make_pair(12, 13), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(13, 13), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(14, 13), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(15, 13), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(16, 13), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(17, 13), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(18, 13), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(19, 13), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(20, 13), std::make_pair(10, 23)),

		std::make_pair(std::make_pair(2, 14), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 14), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(4, 14), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 14), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 14), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 14), std::make_pair(5, 15)),
		std::make_pair(std::make_pair(8, 14), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(9, 14), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(10, 14), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(11, 14), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(12, 14), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(13, 14), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(14, 14), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(15, 14), std::make_pair(9, 22)),
		std::make_pair(std::make_pair(16, 14), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(17, 14), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(18, 14), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(19, 14), std::make_pair(11, 23)),
		std::make_pair(std::make_pair(20, 14), std::make_pair(11, 24)),

		std::make_pair(std::make_pair(2, 15), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 15), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 15), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(5, 15), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 15), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 15), std::make_pair(6, 15)),
		std::make_pair(std::make_pair(8, 15), std::make_pair(6, 16)),
		std::make_pair(std::make_pair(9, 15), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(10, 15), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(11, 15), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(12, 15), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(13, 15), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(14, 15), std::make_pair(9, 22)),
		std::make_pair(std::make_pair(15, 15), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(16, 15), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(17, 15), std::make_pair(11, 23)),
		std::make_pair(std::make_pair(18, 15), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(19, 15), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(20, 15), std::make_pair(12, 25)),

		std::make_pair(std::make_pair(2, 16), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 16), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 16), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(5, 16), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 16), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 16), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(8, 16), std::make_pair(6, 17)),
		std::make_pair(std::make_pair(9, 16), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(10, 16), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(11, 16), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(12, 16), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(13, 16), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(14, 16), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(15, 16), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(16, 16), std::make_pair(11, 23)),
		std::make_pair(std::make_pair(17, 16), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(18, 16), std::make_pair(11, 25)),
		std::make_pair(std::make_pair(19, 16), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(20, 16), std::make_pair(12, 25)),

		std::make_pair(std::make_pair(2, 17), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 17), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 17), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(5, 17), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(6, 17), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 17), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(8, 17), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(9, 17), std::make_pair(7, 18)),
		std::make_pair(std::make_pair(10, 17), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(11, 17), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(12, 17), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(13, 17), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(14, 17), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(15, 17), std::make_pair(11, 23)),
		std::make_pair(std::make_pair(16, 17), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(17, 17), std::make_pair(11, 25)),
		std::make_pair(std::make_pair(18, 17), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(19, 17), std::make_pair(12, 26)),
		std::make_pair(std::make_pair(20, 17), std::make_pair(13, 26)),

		std::make_pair(std::make_pair(2, 18), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 18), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 18), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(5, 18), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(6, 18), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(7, 18), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(8, 18), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(9, 18), std::make_pair(8, 18)),
		std::make_pair(std::make_pair(10, 18), std::make_pair(8, 19)),
		std::make_pair(std::make_pair(11, 18), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(12, 18), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(13, 18), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(14, 18), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(15, 18), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(16, 18), std::make_pair(11, 25)),
		std::make_pair(std::make_pair(17, 18), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(18, 18), std::make_pair(12, 26)),
		std::make_pair(std::make_pair(19, 18), std::make_pair(13, 26)),
		std::make_pair(std::make_pair(20, 18), std::make_pair(13, 27)),

		std::make_pair(std::make_pair(2, 19), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 19), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 19), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(5, 19), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(6, 19), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(7, 19), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(8, 19), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(9, 19), std::make_pair(8, 18)),
		std::make_pair(std::make_pair(10, 19), std::make_pair(8, 20)),
		std::make_pair(std::make_pair(11, 19), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(12, 19), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(13, 19), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(14, 19), std::make_pair(11, 23)),
		std::make_pair(std::make_pair(15, 19), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(16, 19), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(17, 19), std::make_pair(12, 26)),
		std::make_pair(std::make_pair(18, 19), std::make_pair(13, 26)),
		std::make_pair(std::make_pair(19, 19), std::make_pair(13, 27)),
		std::make_pair(std::make_pair(20, 19), std::make_pair(13, 27)),

		std::make_pair(std::make_pair(2, 20), std::make_pair(2, 0)),
		std::make_pair(std::make_pair(3, 20), std::make_pair(3, 0)),
		std::make_pair(std::make_pair(4, 20), std::make_pair(4, 0)),
		std::make_pair(std::make_pair(5, 20), std::make_pair(5, 0)),
		std::make_pair(std::make_pair(6, 20), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(7, 20), std::make_pair(6, 0)),
		std::make_pair(std::make_pair(8, 20), std::make_pair(7, 17)),
		std::make_pair(std::make_pair(9, 20), std::make_pair(8, 18)),
		std::make_pair(std::make_pair(10, 20), std::make_pair(9, 20)),
		std::make_pair(std::make_pair(11, 20), std::make_pair(9, 21)),
		std::make_pair(std::make_pair(12, 20), std::make_pair(10, 22)),
		std::make_pair(std::make_pair(13, 20), std::make_pair(10, 23)),
		std::make_pair(std::make_pair(14, 20), std::make_pair(11, 24)),
		std::make_pair(std::make_pair(15, 20), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(16, 20), std::make_pair(12, 25)),
		std::make_pair(std::make_pair(17, 20), std::make_pair(13, 26)),
		std::make_pair(std::make_pair(18, 20), std::make_pair(13, 27)),
		std::make_pair(std::make_pair(19, 20), std::make_pair(13, 27)),
		std::make_pair(std::make_pair(20, 20), std::make_pair(14, 28))
	};
};
